### ISSUE TITLE
BBpress sensor needs to load on front end

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/wsal-bbpress#23]
A user has pointed out an issue which was a clear oversight on my part I think https://secure.helpscout.net/conversation/1363672301/224?folderId=4248868

When trashing a topic from the "front end" - we get this error 

````
PHP Fatal error: Uncaught Exception: Event with code 8019 has not be registered. in /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php:374
Stack trace:
#0 /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php(370): WSAL_AlertManager->_CommitItem(8019, Array, NULL, false)
#1 /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php(293): WSAL_AlertManager->_CommitItem(8019, Array, NULL)
#2 /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-add-on-for-bbpress/wp-security-audit-log/custom-sensors/BBPressSensor.php(545): WSAL_AlertManager->Trigger(8019, Array)
#3 /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-add-on-for-bbpress/wp-security-audit-log/custom-sensors/BBPressSensor.php(153): WSAL_Sensors_BBPressSensor->EventTopicByCode(Object(WP_Post), 8019)
#4 /nas/content/live/medaorg/wp-includes/class-wp-hook.php(287): WSAL_Sensors_BBPressSensor->EventForumTras in /nas/content/live/medaorg/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php on line 374
````

As soon as I saw the chaps video I knew the problem would be this sensor is only loaded in admin

**Comment by DannyWPWS** [comment]
Closing this up, resolved and confirmed with user (also checked and error does not happen with current develop)
