### ISSUE TITLE
PHP error when trashing/spamming forums

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/wsal-bbpress#40]
Im seeing this error when trashing a post via the front-end

````
[07-Apr-2021 17:46:20 UTC] PHP Fatal error:  Uncaught Exception: Event with code 8019 has not be registered. in /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php:407
Stack trace:
#0 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php(403): WSAL_AlertManager->_CommitItem(8019, Array, NULL, false)
#1 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php(291): WSAL_AlertManager->_CommitItem(8019, Array, NULL)
#2 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wsal-bbpress-master/wp-security-audit-log/custom-sensors/BBPressSensor.php(545): WSAL_AlertManager->Trigger(8019, Array)
#3 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wsal-bbpress-master/wp-security-audit-log/custom-sensors/BBPressSensor.php(153): WSAL_Sensors_BBPressSensor->EventTopicByCode(Object(WP_Pos in /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php on line 407
````

**Comment by DannyWPWS** [comment]
Double checked, this is not happening anymore so closing this up
